# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage
osx_image: xcode9
language: objective-c

env:
- DESTINATION="platform=iOS Simulator,name=iPhone SE"        SCHEME="KRLCollectionViewGridLayout-iOS"
- DESTINATION="platform=tvOS Simulator,name=Apple TV 1080p"  SCHEME="KRLCollectionViewGridLayout-tvOS"

before_install:
- gem update cocoapods --no-rdoc --no-ri --no-document --quiet # Since Travis is not always on latest version
- pod repo update

script:
- pod install
- set -o pipefail && xcodebuild analyze test -workspace KRLCollectionViewGridLayout.xcworkspace -scheme "$SCHEME" -destination "$DESTINATION" GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty -c
- pod lib lint --quick

after_success:
- bash <(curl -s https://codecov.io/bash)
